### PR TITLE
Updated typo in code example.

### PR DESCRIPTION
**Pull request by leonidaspir**
Updated script, rebuilt docs and uploaded, hopefully in the right order. Thanks @willeastcott!

### CODE REVIEW

**Comment by leonidaspir** [comment]
Seems more files have been affected by this PR. Any idea why this internal hashes have been changed with forking?

image

**Comment by willeastcott** [comment]
Oh dear. It looks as though the docs build process will only work if you edit the original repo and not forks. I really don't know how to fix that. Maybe I should just make this fix myself for you. Sorry.

@vkalpias wrote the build process. Let's see what he says on Monday.

**Comment by leonidaspir** [comment]
Great makes sense! Feel free to close this PR.

**Comment by willeastcott** [comment]
Superseded by https://github.com/playcanvas/editor-api/commit/b27c3018b7262cb4abfe0746459fbf46cad733c7

**Pull request closed without merging**
